package acme

import (
	"fmt"
	"strings"
)

var (
	_ interface {
		Error() string
		Errors() []error
	} = (*Problem)(nil)
)

// ErrorType is a type of error defined by [§6.7]
//
// [§6.7]: https://www.rfc-editor.org/rfc/rfc8555#section-6.7
type ErrorType string

const (
	// ErrorAccountDoesNotExist indicates the request specified an
	// account that does not exist
	ErrorAccountDoesNotExist ErrorType = "accountDoesNotExist"

	// ErrorAlreadyRevoked indicates the request specified a
	// certificate to be revoked that has already been revoked
	ErrorAlreadyRevoked ErrorType = "alreadyRevoked"

	// ErrorBadCSR indicates the CSR is unacceptable
	// (e.g., due to a short key)
	ErrorBadCSR ErrorType = "badCSR"

	// ErrorBadNonce indicates the client sent an unacceptable
	// anti-replay nonce
	ErrorBadNonce ErrorType = "badNonce"

	// ErrorBadPublicKey indicates the JWS was signed by a public key
	// the server does not support
	ErrorBadPublicKey ErrorType = "badPublicKey"

	// ErrorBadRevocationReason indicates the revocation reason provided
	// is not allowed by the server
	ErrorBadRevocationReason ErrorType = "badRevocationReason"

	// ErrorBadSignatureAlgorithm indicates the JWS was signed with an
	// algorithm the server does not support
	ErrorBadSignatureAlgorithm ErrorType = "badSignatureAlgorithm"

	// ErrorCAA indicates Certification Authority Authorization (CAA)
	// records forbid the CA from issuing a certificate
	ErrorCAA ErrorType = "caa"

	// ErrorCompound indicates specific error conditions are indicated
	// in the "subproblems" array
	ErrorCompound ErrorType = "compound"

	// ErrorConnection indicates the server could not connect to
	// the validation target
	ErrorConnection ErrorType = "connection"

	// ErrorDNS indicates there was a problem with a DNS query during
	// identifier validation
	ErrorDNS ErrorType = "dns"

	// ErrorExternalAccountRequired indicates the request must include
	// a value for the "externalAccountBinding" field
	ErrorExternalAccountRequired ErrorType = "externalAccountRequired"

	// ErrorIncorrectResponse indicates the response received didn't
	// match the challenge's requirements
	ErrorIncorrectResponse ErrorType = "incorrectResponse"

	// ErrorInvalidContact indicates a contact URL for an account was invalid
	ErrorInvalidContact ErrorType = "invalidContact"

	// ErrorMalformed indicates the request message was malformed
	ErrorMalformed ErrorType = "malformed"

	// ErrorOrderNotReady indicates the request attempted to finalize an order
	// that is not ready to be finalized
	ErrorOrderNotReady ErrorType = "orderNotReady"

	// ErrorRateLimited indicates the request exceeds a rate limit
	ErrorRateLimited ErrorType = "rateLimited"

	// ErrorRejectedIdentifier indicates the server will not issue certificates
	// for the identifier
	ErrorRejectedIdentifier ErrorType = "rejectedIdentifier"

	// ErrorServerInternal indicates the server experienced an internal error
	ErrorServerInternal ErrorType = "serverInternal"

	// ErrorTLS the server received a TLS error during validation
	ErrorTLS ErrorType = "tls"

	// ErrorUnauthorized indicates the client lacks sufficient authorization
	ErrorUnauthorized ErrorType = "unauthorized"

	// ErrorUnsupportedContact indicates a contact URL for an account used
	// an unsupported protocol scheme
	ErrorUnsupportedContact ErrorType = "unsupportedContact"

	// ErrorUnsupportedIdentifier indicates an identifier is of an unsupported
	// type
	ErrorUnsupportedIdentifier ErrorType = "unsupportedIdentifier"

	// ErrorUserActionRequired indicates visit the "instance" URL and take actions
	// specified there
	ErrorUserActionRequired ErrorType = "userActionRequired"
)

// String renders an error type
func (e ErrorType) String() string {
	s := string(e)
	if strings.ContainsRune(s, ':') {
		return s
	}
	return "urn:ietf:params:acme:error:" + s
}

// Problem is an error that occurred while processing
// a request, if any. This field is structured as a problem
// document [RFC7807]
//
// [RFC7807]: https://www.rfc-editor.org/rfc/rfc7807
type Problem struct {
	// Type is a URI that identifies the problem type
	Type ErrorType `json:"type" validate:"uri"`

	// Status is the HTTP status code generated by the server
	// for this occurrence of the problem.
	Status int `json:"status,omitempty"`

	// Detail is a human-readable explanation specific to this
	// occurrence of the problem
	Detail string `json:"detail,omitempty"`

	// Instance is a URI reference that identifies the specific
	// occurrence of the problem.
	Instance string `json:"instance,omitempty" validate:"uri"`

	// Subproblems is an optional slice of particular problems.
	// Subproblems need not all have the same type, and they
	// do not need to match the top level type.
	Subproblems []Problem `json:"subproblems,omitempty"`

	// Identifier refers to the cause of the Problem.
	// The "identifier" field MUST NOT be present at the top
	// level in ACME problem documents.  It can only be
	// present in subproblems.
	Identifier Identifier `json:"identifier,omitempty"`
}

// Error returns the type and details of the Problem
func (p Problem) Error() string {
	t := p.Type.String()
	s := p.Detail
	switch {
	case t != "" && s != "":
		return fmt.Sprintf("%s\n%s", t, s)
	case s != "":
		return s
	default:
		return t
	}
}

// Errors returns the list of subproblems
func (p Problem) Errors() []error {
	var out []error

	if n := len(p.Subproblems); n > 0 {
		out = make([]error, n)
		for i, s := range p.Subproblems {
			out[i] = s
		}
	}

	return out
}
